AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: FastAPI Thumbnail Generator using AWS Lambda and Docker

Resources:
  FastApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: 440744260607.dkr.ecr.us-east-1.amazonaws.com/thumbnail-fastapi-app:latest
      Handler: thumbnail.main.handler  # Ensure this is correct
      MemorySize: 128
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - Policy:
            PolicyName: ThumbnailPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - s3:GetObject
                    - s3:PutObject
                  Resource: arn:aws:s3:::stori-bucket-larc/*
      Environment:
        Variables:
          APP_MODE: production
          DEBUG: "false"
          S3_BUCKET: stori-bucket-larc
          API_KEY: my_stori_api_key  # esto debe ser bajo secret manager!!
      Events:
        UploadApi:
          Type: Api
          Properties:
            Path: /upload
            Method: POST
            RestApiId: !Ref ApiGateway
        HealthCheckApi:
          Type: Api
          Properties:
            Path: /
            Method: GET
            RestApiId: !Ref ApiGateway
        SecureDataApi:
          Type: Api
          Properties:
            Path: /secure-data
            Method: GET
            RestApiId: !Ref ApiGateway

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'OPTIONS,POST,GET'"  # 
        AllowHeaders: "'Content-Type,X-API-KEY'"  # 
        AllowOrigins: "'*'"  # 

Outputs:
  FastApiFunction:
    Description: FastAPI Lambda Function ARN
    Value: !GetAtt FastApiFunction.Arn
